// tarot-deck.js
// This holds all 78 cards. The main script will pull from this array.

const tarotDeck = [
  // --- MAJOR ARCANA ---
  { name: "The Fool", past: "You stepped off a ledge without checking the drop.", present: "You are untethered, floating in the static.", future: "A new beginning, or perhaps just a longer fall." },
  { name: "The Magician", past: "You rearranged the room to suit your needs.", present: "You see the seams of this place and manipulate the echoes.", future: "You will build a door where there was only a wall." },
  { name: "The High Priestess", past: "You kept a secret that wasn't yours.", present: "Sitting in the quiet, listening to the hum of the lights.", future: "An intuition will guide you through the locked doors." },
  { name: "The Empress", past: "A memory of warmth, like tea left on a desk.", present: "Nurturing the fragments of this space.", future: "Growth, even in the cracks of the floorboards." },
  { name: "The Emperor", past: "You built rules to keep yourself safe.", present: "Demanding order in a place that defies physics.", future: "A rigid structure that will either hold or break." },
  { name: "The Hierophant", past: "You sought answers from someone who wasn't there.", present: "Conforming to the waiting room's unspoken laws.", future: "A lesson learned through strict repetition." },
  { name: "The Lovers", past: "Two chairs facing each other, but only one indent.", present: "A choice between holding on and letting go.", future: "A union of past and present, for better or worse." },
  { name: "The Chariot", past: "You rushed forward blindly.", present: "Moving through the halls with sudden momentum.", future: "Tearing down the wallpaper to push forward." },
  { name: "Strength", past: "You carried something far too heavy.", present: "Enduring the quiet without breaking.", future: "Taming the shadows in the corner of the ceiling." },
  { name: "The Hermit", past: "You isolated yourself on purpose.", present: "Holding a lantern in an endless, empty corridor.", future: "Finding the answer only when everyone else is gone." },
  { name: "Wheel of Fortune", past: "A sudden shift left you dizzy.", present: "The clock ticks, but the hands don't move.", future: "A cycle repeating itself until you break it." },
  { name: "Justice", past: "A consequence you knew was coming.", present: "Weighing the echoes you've gathered.", future: "The scales will balance, regardless of what you want." },
  { name: "The Hanged Man", past: "You gave up control to see what would happen.", present: "Suspended in time, viewing the room upside down.", future: "A sacrifice required to open the next door." },
  { name: "Death", past: "An ending that felt like a locked door.", present: "Shedding an old habit that no longer serves you.", future: "Not a finale, just the closing of the current loop." },
  { name: "Temperance", past: "You poured the tea carefully, balancing the heat.", present: "Finding equilibrium in the liminal drift.", future: "A quiet peace found by mixing opposing forces." },
  { name: "The Devil", past: "You signed a lease for a room you couldn't leave.", present: "Chained to a desk by your own volition.", future: "Breaking a bond that felt impossible to snap." },
  { name: "The Tower", past: "The ceiling painted to look like a sky fell down.", present: "Sudden chaos; the static grows deafening.", future: "A violent realization that tears the room apart." },
  { name: "The Star", past: "A moment of clarity in the fog.", present: "Pouring out the moon tears, finding hope.", future: "A guiding light out of the waiting room." },
  { name: "The Moon", past: "You mistook a shadow for a friend.", present: "Illusion. You are blending perfectly into the pastel wallpaper.", future: "Navigating by a light that constantly shifts." },
  { name: "The Sun", past: "A sudden exposure to the truth.", present: "The light hurts your eyes, but it's real.", future: "Absolute clarity, burning away the fog." },
  { name: "Judgement", past: "A final decision was made.", present: "Listening for a calling from the other side of the glass.", future: "Rising up from the ashes of the old room." },
  { name: "The World", past: "A cycle completed itself.", present: "The hallway loops back on itself; emptiness is complete.", future: "You belong to the corridor now. Total integration." },

  // --- MINOR ARCANA (WANDS) ---
  { name: "Ace of Wands", past: "A spark of inspiration.", present: "New energy flowing.", future: "A sudden creative urge." },
  { name: "Two of Wands", past: "Planning a route.", present: "Looking out the window.", future: "A decision to leave." },
  { name: "Three of Wands", past: "Waiting for a ship.", present: "Expanding horizons.", future: "A journey begins." },
  { name: "Four of Wands", past: "A small celebration.", present: "Finding a temporary home.", future: "Stability in transit." },
  { name: "Five of Wands", past: "A minor conflict.", present: "Clashing thoughts.", future: "Overcoming petty struggles." },
  { name: "Six of Wands", past: "A quiet victory.", present: "Recognition.", future: "Success." },
  { name: "Seven of Wands", past: "Defending your space.", present: "Holding your ground.", future: "Perseverance against odds." },
  { name: "Eight of Wands", past: "Rapid movement.", present: "Things happening quickly.", future: "A sudden message." },
  { name: "Nine of Wands", past: "Exhaustion.", present: "Guarding the door.", future: "One last push." },
  { name: "Ten of Wands", past: "Carrying too much.", present: "Heavy burdens.", future: "Release of duty." },
  { name: "Page of Wands", past: "A curious thought.", present: "Exploring a new hall.", future: "An exciting prospect." },
  { name: "Knight of Wands", past: "Impulsive action.", present: "Charging forward.", future: "A passionate endeavor." },
  { name: "Queen of Wands", past: "Warmth and confidence.", present: "Fierce independence.", future: "Commanding the space." },
  { name: "King of Wands", past: "Taking charge.", present: "Leading the way.", future: "Bold authority." },

  // --- MINOR ARCANA (CUPS) ---
  { name: "Ace of Cups", past: "An emotional awakening.", present: "A cup overflowing.", future: "Deep connection." },
  { name: "Two of Cups", past: "A shared moment.", present: "Mutual understanding.", future: "A partnership." },
  { name: "Three of Cups", past: "Joyful reunion.", present: "Celebrating with ghosts.", future: "Friendship." },
  { name: "Four of Cups", past: "Boredom.", present: "Rejecting what is offered.", future: "A missed opportunity." },
  { name: "Five of Cups", past: "Grief over what spilled.", present: "Focusing on the loss.", future: "Moving past regret." },
  { name: "Six of Cups", past: "Nostalgia.", present: "Looking at old polaroids.", future: "A return to the past." },
  { name: "Seven of Cups", past: "Too many choices.", present: "Illusions and daydreams.", future: "Finding reality in the fog." },
  { name: "Eight of Cups", past: "Walking away.", present: "Leaving the cups behind.", future: "A search for deeper meaning." },
  { name: "Nine of Cups", past: "A wish granted.", present: "Smug satisfaction.", future: "Emotional fulfillment." },
  { name: "Ten of Cups", past: "Total happiness.", present: "Harmony in the room.", future: "Lasting peace." },
  { name: "Page of Cups", past: "A gentle surprise.", present: "A quiet apology.", future: "An emotional message." },
  { name: "Knight of Cups", past: "A romantic ideal.", present: "Following your heart.", future: "A graceful arrival." },
  { name: "Queen of Cups", past: "Deep empathy.", present: "Understanding the silence.", future: "Emotional intuition." },
  { name: "King of Cups", past: "Emotional control.", present: "Calm waters.", future: "Mastery of feelings." },

  // --- MINOR ARCANA (SWORDS) ---
  { name: "Ace of Swords", past: "A sharp realization.", present: "Cutting through the static.", future: "Absolute truth." },
  { name: "Two of Swords", past: "A stalemate.", present: "Blindfolded at the desk.", future: "A difficult choice." },
  { name: "Three of Swords", past: "Heartbreak.", present: "A piercing sorrow.", future: "Painful clarity." },
  { name: "Four of Swords", past: "Forced rest.", present: "Lying completely still.", future: "Recovery." },
  { name: "Five of Swords", past: "A hollow victory.", present: "Conflict at a cost.", future: "Walking away from a fight." },
  { name: "Six of Swords", past: "Leaving troubled waters.", present: "Drifting to a quiet shore.", future: "A calm transition." },
  { name: "Seven of Swords", past: "Deception.", present: "Sneaking out the back.", future: "A strategic retreat." },
  { name: "Eight of Swords", past: "Feeling trapped.", present: "Tied up by your own thoughts.", future: "Realizing you hold the key." },
  { name: "Nine of Swords", past: "Nightmares.", present: "Anxiety keeping you awake.", future: "Facing your fears." },
  { name: "Ten of Swords", past: "Rock bottom.", present: "An absolute ending.", future: "Nowhere to go but up." },
  { name: "Page of Swords", past: "A sharp remark.", present: "Curiosity and vigilance.", future: "A swift message." },
  { name: "Knight of Swords", past: "Rushing into battle.", present: "Aggressive action.", future: "A swift conclusion." },
  { name: "Queen of Swords", past: "Cold logic.", present: "Cutting out the nonsense.", future: "Clear, unbiased judgement." },
  { name: "King of Swords", past: "Intellectual authority.", present: "Ruling with the mind.", future: "Absolute clarity of thought." },

  // --- MINOR ARCANA (PENTACLES) ---
  { name: "Ace of Pentacles", past: "A new physical grounding.", present: "A solid foundation.", future: "Manifesting reality." },
  { name: "Two of Pentacles", past: "Juggling priorities.", present: "Balancing the drift.", future: "Adaptability." },
  { name: "Three of Pentacles", past: "Building something.", present: "Working on the architecture.", future: "Mastery of your craft." },
  { name: "Four of Pentacles", past: "Hoarding echoes.", present: "Holding on too tightly.", future: "Financial or physical blockages." },
  { name: "Five of Pentacles", past: "Left out in the cold.", present: "Feeling isolated.", future: "Seeking shelter." },
  { name: "Six of Pentacles", past: "Giving and taking.", present: "A fair exchange.", future: "Generosity." },
  { name: "Seven of Pentacles", past: "Waiting for a return.", present: "Assessing the harvest.", future: "Patience pays off." },
  { name: "Eight of Pentacles", past: "Repetitive work.", present: "Focusing on the details.", future: "Skill development." },
  { name: "Nine of Pentacles", past: "Enjoying the fruits of labor.", present: "Solitary comfort.", future: "Luxury." },
  { name: "Ten of Pentacles", past: "A lasting legacy.", present: "Complete stability.", future: "Wealth and permanence." },
  { name: "Page of Pentacles", past: "A new study.", present: "Fascination with the physical.", future: "A grounded message." },
  { name: "Knight of Pentacles", past: "Slow, steady progress.", present: "Grinding away.", future: "Reliability." },
  { name: "Queen of Pentacles", past: "Practical nurturing.", present: "Making the room a home.", future: "Sensual comfort." },
  { name: "King of Pentacles", past: "Material success.", present: "Providing absolute security.", future: "A steadfast foundation." }
];

